CREATE TABLE IF NOT EXISTS user_actions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT           NOT NULL,
    event_id   BIGINT           NOT NULL,
    total_weight DOUBLE PRECISION NOT NULL,
    timestamp  TIMESTAMP        NOT NULL
);

CREATE TABLE IF NOT EXISTS event_similarities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a   BIGINT           NOT NULL,
    event_b   BIGINT           NOT NULL,
    score     DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP        NOT NULL
);