spring:
  jpa:
  hibernate:
    ddl-auto: none
    format_sql: true
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/core_db
    username: dbuser
    password: 12345

eureka:
  client:
    service-url:
      default-zone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.fasterxml.jackson: DEBUG
    org.springframework.web: DEBUG
server:
  port: 0