spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/infra/{application}
            - classpath:config/core/{application}
            - classpath:config/stats/{application}

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
      instance:
        prefer-ip-address: true
