services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections (external)
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: K0EA9p0yEe6MkAAAAkKsEg
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:29092 --list || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      kafka:
        condition: service_healthy
    command: |
      bash -c "
        kafka-topics --create --topic stats.user-actions.v1 \
                     --partitions 1 --replication-factor 1 --if-not-exists \
                     --bootstrap-server kafka:29092 && \
        kafka-topics --create --topic stats.events-similarity.v1 \
                     --partitions 1 --replication-factor 1 --if-not-exists \
                     --bootstrap-server kafka:29092
      "
    init: true
  discovery-server:
    build: ./infra/discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  config-server:
    build: ./infra/config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE: http://discovery-server:8761/eureka
    networks:
      - app-network

  gateway-server:
    build: ./infra/gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE: http://discovery-server:8761/eureka
    networks:
      - app-network

  stats-server:
    build: ./stats/stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE: http://discovery-server:8761/eureka
    depends_on:
      discovery-server:
        condition: service_healthy
      gateway-server:
        condition: service_started
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    hostname: stats-db
    ports:
      - "5432:5432"
      #volumes:
      # - ./volumes/postgres-stats:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -d "$$POSTGRES_DB" -U "$$POSTGRES_USER"
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - app-network
  core-db:
    image: postgres:16.1
    container_name: core-db
    hostname: core-db
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5431:5432"
    healthcheck:
      test: pg_isready -q -d "$$POSTGRES_DB" -U "$$POSTGRES_USER"
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - app-network
  analyzer-db:
    image: postgres:16.1
    container_name: analyzer-db
    hostname: analyzer-db
    environment:
      POSTGRES_DB: analyzer
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5430:5432"
    healthcheck:
      test: pg_isready -q -d "$$POSTGRES_DB" -U "$$POSTGRES_USER"
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

