services:
  discovery-server:
    build: ./infra/discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  config-server:
    build: ./infra/config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE: http://discovery-server:8761/eureka
    networks:
      - app-network

  gateway-server:
    build: ./infra/gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE: http://discovery-server:8761/eureka
    networks:
      - app-network

  stats-server:
    build: ./stats/stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE: http://discovery-server:8761/eureka
    depends_on:
      discovery-server:
        condition: service_healthy
      gateway-server:
        condition: service_started
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    hostname: stats-db
    ports:
      - "5432:5432"
      #volumes:
      # - ./volumes/postgres-stats:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -d "$$POSTGRES_DB" -U "$$POSTGRES_USER"
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - app-network

  main-service:
    build: ./core/main-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://core-db:5432/core_db
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULT_ZONE: http://discovery-server:8761/eureka
    depends_on:
      discovery-server:
        condition: service_healthy
      gateway-server:
        condition: service_started
      core-db:
        condition: service_healthy
    networks:
      - app-network

  core-db:
    image: postgres:16.1
    container_name: core-db
    hostname: core-db
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5431:5432"
    healthcheck:
      test: pg_isready -q -d "$$POSTGRES_DB" -U "$$POSTGRES_USER"
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

