kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    retries: 0
  topics:
    output: stats.user-actions.v1

main:
  allow-bean-definition-overriding: true
server:
  port: 0

grpc:
  server:
    port: 0

