spring:
  application:
    name: stats-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: false
      retry:
        use-random-policy: true
        max-interval: 6000
