spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/core_db
    username: dbuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    format_sql: true
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: false


logging:
  level:
    com.fasterxml.jackson: DEBUG
    org.springframework.web: DEBUG
server:
  port: 0