spring:
  application:
    name: gateway-server

  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: false
      retry:
        useRandomPolicy: true
        max-interval: 6000

