server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

spring:
  cloud:
    gateway:
      routes:
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**
          filters:
            - StripPrefix=0
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - StripPrefix=0
        - id: categories-service
          uri: lb://categories-service
          predicates:
            - Path=/categories/**, /admin/categories/**
          filters:
            - StripPrefix=0
        - id: compilation-service
          uri: lb://compilation-service
          predicates:
            - Path=/compilations/**, /admin/compilations/**
          filters:
            - StripPrefix=0
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**, users/{userId}/events/**, /admin/events/**
          filters:
            - StripPrefix=0



